### ISSUE TITLE
怎么不更新了？(QWQ)

### ISSUE THREAD

**Issue by FiCn7430** [Vera-Firefly/PZH-X-PGW#1]

**Comment by Vera-Firefly** [comment]
抱歉,PZH · PGW由于一些因素无法更新,得等墨北优化好了他那个我这里才能进行更新

**Comment by FiCn7430** [comment]
很看好这个魔改版本，加油

**Comment by Vera-Firefly** [comment]
> 很看好这个魔改版本，加油

你可以先用着[Pojav Glow·Worm](https://github.com/Vera-Firefly/Pojav-Glow-Worm)

**Comment by FiCn7430** [comment]
我是PGW的老用户啊

**Comment by FiCn7430** [comment]
可不可以考虑加入一个新功能，就是可以用户自由导入加载第三方so库，比如一些模组会调用或加载自带的so库，但PGW不会去加载这些，那就需要去改源码导入so库，很不方便。

**Comment by FiCn7430** [comment]
？
